Add ClayTech
TheBusyBiscuit/builds pull request #33
Opened 2020-08-28 14:20 UTC by ClayCoffee

2020-08-28 17:50 UTC, TheBusyBiscuit requested changes

2020-08-28 17:50 UTC, TheBusyBiscuit commented on resources/repos.json
> +			"prefix": "DEVR"
Why "DEVR"?

2020-08-28 17:50 UTC, TheBusyBiscuit commented on resources/repos.json
> +	"ClayCoffee/ClayTech:master": {
Can you please move this to the bottom of the file? I'd like to keep the order universal and just append new ones at the end.

2020-08-29 06:07 UTC, ClayCoffee reviewed
ok

2020-08-29 09:37 UTC, TheBusyBiscuit approved these changes

2020-08-29 09:37 UTC, merged