Update SFCalc entry... again
TheBusyBiscuit/builds pull request #39
Opened 2020-09-07 13:14 UTC by Seggan

## Description
Updated SF version

## Reason
New SF version (RC-16) came out

2020-09-07 18:51 UTC, TheBusyBiscuit requested changes

2020-09-07 18:51 UTC, TheBusyBiscuit commented on resources/repos.json
> +				"5": "<a class=\"link_info\" href=\"/builds/TheBusyBiscuit/CS-CoreLib/master/#90\">dev #90</a>"
Missing comma at the end

2020-09-07 18:51 UTC, TheBusyBiscuit commented on resources/repos.json
> +				"5": "<a class=\"link_info\" href=\"/builds/TheBusyBiscuit/Slimefun4/stable/#16\">RC-16</a>"
Missing comma at the end

2020-09-09 01:50 UTC, Seggan commented
Done

2020-09-09 11:01 UTC, merged