Add GeneticChickengineering
TheBusyBiscuit/builds pull request #71
Opened 2021-01-30 22:00 UTC by kii-chan-reloaded

## Description
This adds Genetic Chickengineering to the build server.

## Reason
Having automatic development builds will lighten the load on me to keep pushing releases for every point update. It was also suggested by @Seggan

2021-01-30 22:48 UTC, kii-chan-reloaded commented
I couldn't figure out why all my builds were failing despite being valid JSON. Turns out a commit from a few days ago to `schema.json` had a missing quotation mark. May as well add that to this pull, I guess.

2021-01-30 23:29 UTC, TheBusyBiscuit commented on resources/schema.json
> +              "type": "boolean"
Whooops thanks 😅

2021-01-30 23:29 UTC, TheBusyBiscuit commented on resources/repos.json
> +            }
Pretty sure your plugin requires Paper to be used, right?
If so, then you should add this as a dependency here.

2021-01-31 00:02 UTC, TheBusyBiscuit requested changes

2021-01-31 00:02 UTC, TheBusyBiscuit commented on resources/repos.json
>              }
Missing comma

2021-01-31 00:05 UTC, TheBusyBiscuit approved these changes

2021-01-31 00:05 UTC, merged